INSERT INTO `users` (`id`,`name`,`weight`,`height`,`age`) VALUES (2,'Virendra Singh','80 Kg','172',37);
INSERT INTO `users` (`id`,`name`,`weight`,`height`,`age`) VALUES (3,'Griva Singh','21 Kg','169',6);
INSERT INTO `users` (`id`,`name`,`weight`,`height`,`age`) VALUES (4,'Abhay Singh','21 Kg','169',6);
INSERT INTO `users` (`id`,`name`,`weight`,`height`,`age`) VALUES (7,'Vijay Singh','21 Kg','169',6);
INSERT INTO `users` (`id`,`name`,`weight`,`height`,`age`) VALUES (8,'Abhay Singh','21 Kg','169',6);
INSERT INTO `users` (`id`,`name`,`weight`,`height`,`age`) VALUES (9,'Vijay Singh','21 Kg','169',6);
INSERT INTO `users` (`id`,`name`,`weight`,`height`,`age`) VALUES (10,'Abhay Singh','21 Kg','169',6);
INSERT INTO `users` (`id`,`name`,`weight`,`height`,`age`) VALUES (11,'Vijay Singh','21 Kg','169',6);
INSERT INTO `users` (`id`,`name`,`weight`,`height`,`age`) VALUES (12,'Ravi Kumar','9 Kg','123',27);
INSERT INTO `users` (`id`,`name`,`weight`,`height`,`age`) VALUES (13,'Vijay Singh','21 Kg','169',6);
INSERT INTO `users` (`id`,`name`,`weight`,`height`,`age`) VALUES (14,'Anirudh','30Kg','116',9);
